networks:
  - name: private
    type: dynamic
    cloud_properties:
      vswitch_id: ((subnet_id))
      security_group_id: ((security_group_id))
  - name: vip
    type: vip

vm_types:
  - name: default
    cloud_properties: &default_cloud_properties
      instance_type: ecs.sn2.medium
      availability_zone: ((az))
  - name: slb_registration_pool
    cloud_properties:
      <<: *default_cloud_properties
      slbs: [((slb_http_id))]

compilation:
  reuse_compilation_vms: true
  workers: 1
  network: private
  cloud_properties:
    instance_type: ecs.sn2.medium
    availability_zone: ((az))
