networks:
  - name: private
    type: dynamic
    cloud_properties:
      vswitch_id: ((vswitch_id))
      security_group_id: ((security_group_id))
  - name: vip
    type: vip
#  - name: compile_vip
#    type: vip
#    cloud_properties:
#      static_ips: [((external_0_ip_address))]
#      default: [dns, gateway]

vm_types:
  - name: default
    cloud_properties: &default_cloud_properties
      instance_type: ecs.sn2.medium
      availability_zone: ((availability_zone))
  - name: slb_registration_pool
    cloud_properties:
      <<: *default_cloud_properties
      slbs: [((slb_http_id))]

compilation:
  reuse_compilation_vms: true
  workers: 1
  network: private
  cloud_properties:
    instance_type: ecs.sn2.medium
    availability_zone: ((availability_zone))
