networks:
  - name: private
    type: dynamic
    cloud_properties:
      subnet: ((subnet_id))

vm_types:
  - name: default
    cloud_properties: &default_cloud_properties
      instance_type: t2.medium
      availability_zone: ((az))
  - name: iam_role
    cloud_properties:
      <<: *default_cloud_properties
      iam_instance_profile: ((iam_instance_profile))
  - name: raw_ephemeral_pool
    cloud_properties:
      instance_type: m3.medium
      availability_zone: ((az))
      raw_instance_storage: true
  - name: elb_registration_pool
    cloud_properties:
      <<: *default_cloud_properties
      elbs: [((e2e_elb_name))]
  - name: spot_instance_pool
    cloud_properties:
      <<: *default_cloud_properties
      instance_type: m4.large
      spot_bid_price: 0.10 # 10x the normal bid price

compilation:
  reuse_compilation_vms: true
  workers: 1
  network: private
  cloud_properties:
    instance_type: t2.medium
    availability_zone: ((az))