networks:
  - name: private
    type: dynamic
    cloud_properties:
      subnet: ((subnet_id))

vm_types:
  - name: default
    cloud_properties: &default_cloud_properties
      instance_type: ecs.sn2.medium
      availability_zone: ((az))
  - name: slb_registration_pool
    cloud_properties:
      <<: *default_cloud_properties
      #slbs: [((e2e_elb_name))]
      #todo: wait for terraform put it in metadata
      slbs: ["lb-2zepxu7karjqfzw2q2oe2"]

compilation:
  reuse_compilation_vms: true
  workers: 1
  network: private
  cloud_properties:
    instance_type: ecs.sn2.medium
    availability_zone: ((az))
