---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/gce-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: go-cpi-blobs
  - name: version-semver

outputs:
  - name: candidate

#run:
#  path: bosh-cpi-src/ci/tasks/build-candidate.sh

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/build-candidate.sh
    bash bosh-cpi-src/ci/tasks/build-candidate.sh