---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: version-semver

outputs:
  - name: candidate

#run:
#  path: bosh-cpi-src/ci/tasks/build-candidate.sh

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/build-candidate.sh
    spawn dpkg-reconfigure dash
    expect "Use dash as the default system shell (/bin/sh)?"
    send "no"
    send "\n"
    . bosh-cpi-src/ci/tasks/build-candidate.sh