---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: terraform
  - name: terraform-provider
  - name: terraform-module
  - name: terraform-task

outputs:
  - name: terraform-env

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x terraform-task/build-environment.sh
    terraform-task/build-environment.sh

params:
  ALICLOUD_ACCESS_KEY_ID:     ""
  ALICLOUD_SECRET_ACCESS_KEY: ""
  ALICLOUD_DEFAULT_REGION:    ""