---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}
inputs:
  - name: bosh-cpi-src
  - name: bosh-cpi-release
  - name: release-version-semver
outputs:
  - name: promoted
run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/promote-candidate.sh
    bash bosh-cpi-src/ci/tasks/promote-candidate.sh
params:
  ALICLOUD_ACCESS_KEY_ID:     ""
  ALICLOUD_ACCESS_KEY_SECRET: ""