---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: bosh-cpi-src
  - name: terraform-metadata
  - name: stemcell
  - name: heavy-stemcell
  - name: bosh-cli
  - name: director-state
  - name: jq-blob
  - name: libffi-blob
  - name: libpqxx-blob
  - name: pip-blob
  - name: python-blob
  - name: core-blob
  - name: slb-blob

run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/run-e2e.sh
    bash bosh-cpi-src/ci/tasks/run-e2e.sh

params:
  BOSH_DEBUG_LEVEL: info