---
platform: linux

image_resource:
  type: docker-image
  source: {repository: boshcpi/aws-cpi-release}

inputs:
  - name: bosh-cpi-src
#  - name: environment
  - name: stemcell
  - name: heavy-stemcell
  - name: bosh-cli
  - name: director-state

run:
  path: bosh-cpi-src/ci/tasks/run-e2e.sh

params:
  BOSH_DEBUG_LEVEL: info