---
platform: linux
image_resource:
  type: docker-image
  source: {repository: boshcpi/gce-cpi-release}
inputs:
  - name: bosh-cpi-src
  - name: stemcell
  - name: terraform-metadata
run:
  path: sh
  args:
  - -exc
  - |
    chmod +x bosh-cpi-src/ci/tasks/run-integration.sh
    bash bosh-cpi-src/ci/tasks/run-integration.sh
params:
  ALICLOUD_ACCESS_KEY_ID:     ""
  ALICLOUD_SECRET_ACCESS_KEY: ""
  ALICLOUD_DEFAULT_REGION:    ""
  CPI_STEMCELL_ID:            ""
  CPI_INTERNAL_IP:            ""
  CPI_INTERNAL_GW:            ""